### ISSUE TITLE
被规范代码没有下划波浪线提示

### ISSUE THREAD

**Issue by hfg5961107** [Omooo/CustomLint#1]
请问我按照流程编写后，执行gradlew lint 能出xml等。但是问题代码并没有下划波浪线等显示或者提示。问题出在那个地方呢？

https://app.leanboard.io/board/1798343d-f0c2-4aad-9b7a-229d7f5553be

**Comment by Omooo** [comment]
你好：
你的这个问题我也遇到过，写完发现没有警告提示。
首先 Lint API 目前还并不是稳定 API，可以看到每个文件头都有 UnstableApiUsage 标示，并不保证一定就会有警告提示，特别是布局文件中的 Detector，代码文件的 Detector 还好，但是也有少数情况下不能立即生效。
最开始我是多次改 Detector 的代码，发现并没有效果，但是运行 lint 看到是有的，这个时候往往需要你先 lintChecks 再同步一下工程，然后在写可被监测到的代码，然后发现就有了。
对于很严重的错误，可以指定为 Error 级别，在编译时也能够中断编译，并且可看到 Error 级别的代码路径。

**Comment by hfg5961107** [comment]
请问lintChecks是指使用Inspect Code检查一次代码还是指执行gradlew lint？我这些操作过后同步了工程。还是没有效果。无论是项目中布局文件Detector还是java文件的。请问你对目前的情况有一些什么更好的想法或者建议么？

**Comment by Omooo** [comment]
lintChecks 是指 lintChecks project(":lint_library") 这行代码，当你改完/写完 Detector 之后，先同步一下工程。
对于这种情况，其实也并没有什么好的建议。
好一点的实践就是分清监测的等级和类型，如果是较为严重的，指定 Error 级别，这样在你编译打包时会中断编译并提示错误代码路径，如果是不太严重但是就是想要规范写法的话，可以指定为同一个类型，在输出 html 的时候可以看到同类型的，查看输出到 html 是比较清楚的，html 记得要用浏览器打开哦。
