### ISSUE TITLE
xml文件无法识别

### ISSUE THREAD

**Issue by laiyi55** [Omooo/CustomLint#2]
我把编译好jar放到相关目录下，其他都能生效，但是layout目录里面的xml的ImageView的src使用了png未被检测出来，这是为什么？

**Comment by laiyi55** [comment]
我发现是不能在页面上提示出来，只能使用Inspect Tool发现

**Comment by Omooo** [comment]
你好：
我也遇到这个问题，主要是目前 API 并不稳定，你可以看到在你写的 Detector 类都会有一个注解，表明该类 API 并不稳定，所以有时候这个问题还真没办法，只能通过执行 lint 输出查看。

这个 ISSUE 或许对你也有帮助：
https://github.com/Omooo/CustomLint/issues/1
