### ISSUE TITLE
请问下lintchecks设置

### ISSUE THREAD

**Issue by corresponding** [Omooo/CustomLint#3]
大佬，我是从这篇文章过来的，看到评论里面你有说lint checks
https://juejin.im/post/5d307615f265da1b6b1d0dd9

是否转成aar后，无法使用lintChecks，只能使用implement？

**Comment by Omooo** [comment]
这个我只是在本地 module 写的，所以 lintChecks 依赖之后，在改 module 可以实时生效的，没试过打包成 AAR，见谅~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"corresponding"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 下午5:26
收件人:&nbsp;"Omooo/CustomLint"<CustomLint@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Omooo/CustomLint] 请问下lintchecks设置 (#3)





 
大佬，我是从这篇文章过来的，看到评论里面你有说lint checks
 https://juejin.im/post/5d307615f265da1b6b1d0dd9
 
是否转成aar后，无法使用lintChecks，只能使用implement？

**Comment by Omooo** [comment]
想起来了，以前低版本 AS 的确是需要打包的，而高版本 AS （3.0+）就可以直接&nbsp;lintChecks 依赖了，我掘金有这篇文章的。
或者在我 GitHub 看：https://github.com/Omooo/CustomLint




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"corresponding"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 下午5:26
收件人:&nbsp;"Omooo/CustomLint"<CustomLint@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Omooo/CustomLint] 请问下lintchecks设置 (#3)





 
大佬，我是从这篇文章过来的，看到评论里面你有说lint checks
 https://juejin.im/post/5d307615f265da1b6b1d0dd9
 
是否转成aar后，无法使用lintChecks，只能使用implement？

**Comment by corresponding** [comment]
这么来说高版本AS，就没什么必要打成aar包了？

**Comment by Omooo** [comment]
是的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"corresponding"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 下午5:38
收件人:&nbsp;"Omooo/CustomLint"<CustomLint@noreply.github.com&gt;;
抄送:&nbsp;"沐小晨曦"<869759698@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Omooo/CustomLint] 请问下lintchecks设置 (#3)





 
这么来说高版本AS，就没什么必要打成aar包了？

**Comment by corresponding** [comment]
嗯嗯，aar可能是为了解决以前AS2的project问题
谢谢大佬了~
